// Copyright 2026 The gofreetype Authors. All rights reserved.
// Use of this source code is governed by your choice of either the
// FreeType License or the GNU General Public License version 2 (or
// any later version), both of which can be found in the LICENSE file.

package cff

// standardStrings is the list of 391 predefined CFF strings (SID 0..390).
// Index (the SID) maps directly to the corresponding PostScript name.
// See Adobe Technical Note #5176, Appendix A.
var standardStrings = [...]string{
	".notdef", "space", "exclam", "quotedbl", "numbersign",
	"dollar", "percent", "ampersand", "quoteright", "parenleft",
	"parenright", "asterisk", "plus", "comma", "hyphen",
	"period", "slash", "zero", "one", "two",
	"three", "four", "five", "six", "seven",
	"eight", "nine", "colon", "semicolon", "less",
	"equal", "greater", "question", "at", "A",
	"B", "C", "D", "E", "F",
	"G", "H", "I", "J", "K",
	"L", "M", "N", "O", "P",
	"Q", "R", "S", "T", "U",
	"V", "W", "X", "Y", "Z",
	"bracketleft", "backslash", "bracketright", "asciicircum", "underscore",
	"quoteleft", "a", "b", "c", "d",
	"e", "f", "g", "h", "i",
	"j", "k", "l", "m", "n",
	"o", "p", "q", "r", "s",
	"t", "u", "v", "w", "x",
	"y", "z", "braceleft", "bar", "braceright",
	"asciitilde", "exclamdown", "cent", "sterling", "fraction",
	"yen", "florin", "section", "currency", "quotesingle",
	"quotedblleft", "guillemotleft", "guilsinglleft", "guilsinglright", "fi",
	"fl", "endash", "dagger", "daggerdbl", "periodcentered",
	"paragraph", "bullet", "quotesinglbase", "quotedblbase", "quotedblright",
	"guillemotright", "ellipsis", "perthousand", "questiondown", "grave",
	"acute", "circumflex", "tilde", "macron", "breve",
	"dotaccent", "dieresis", "ring", "cedilla", "hungarumlaut",
	"ogonek", "caron", "emdash", "AE", "ordfeminine",
	"Lslash", "Oslash", "OE", "ordmasculine", "ae",
	"dotlessi", "lslash", "oslash", "oe", "germandbls",
	"onesuperior", "twosuperior", "threesuperior", "minus", "multiply",
	"onehalf", "onequarter", "threequarters", "questiondownsmall", "brokenbar",
	"copyright", "registered", "trademark", "cent.oldstyle", "dollar.oldstyle",
	"Gravesmall", "Asmall", "Bsmall", "Csmall", "Dsmall",
	"Esmall", "Fsmall", "Gsmall", "Hsmall", "Ismall",
	"Jsmall", "Ksmall", "Lsmall", "Msmall", "Nsmall",
	"Osmall", "Psmall", "Qsmall", "Rsmall", "Ssmall",
	"Tsmall", "Usmall", "Vsmall", "Wsmall", "Xsmall",
	"Ysmall", "Zsmall", "colonmonetary", "onefitted", "rupiah",
	"Tildesmall", "exclamdownsmall", "centoldstyle", "Lslashsmall",
	"Scaronsmall", "Zcaronsmall", "Dieresissmall", "Brevesmall", "Caronsmall",
	"Dotaccentsmall", "Macronsmall", "figuredash", "hypheninferior", "Ogoneksmall",
	"Ringsmall", "Cedillasmall", "questiondownsmall", "oneeighth", "threeeighths",
	"fiveeighths", "seveneighths", "onethird", "twothirds", "zerosuperior",
	"foursuperior", "fivesuperior", "sixsuperior", "sevensuperior", "eightsuperior",
	"ninesuperior", "zeroinferior", "oneinferior", "twoinferior", "threeinferior",
	"fourinferior", "fiveinferior", "sixinferior", "seveninferior", "eightinferior",
	"nineinferior", "centinferior", "dollarinferior", "periodinferior", "commainferior",
	"Agravesmall", "Aacutesmall", "Acircumflexsmall", "Atildesmall", "Adieresissmall",
	"Aringsmall", "AEsmall", "Ccedillasmall", "Egravesmall", "Eacutesmall",
	"Ecircumflexsmall", "Edieresissmall", "Igravesmall", "Iacutesmall", "Icircumflexsmall",
	"Idieresissmall", "Ethsmall", "Ntildesmall", "Ogravesmall", "Oacutesmall",
	"Ocircumflexsmall", "Otildesmall", "Odieresissmall", "OEsmall", "Oslashsmall",
	"Ugravesmall", "Uacutesmall", "Ucircumflexsmall", "Udieresissmall", "Yacutesmall",
	"Thornsmall", "Ydieresissmall", "001.000", "001.001", "001.002",
	"001.003", "Black", "Bold", "Book", "Light",
	"Medium", "Regular", "Roman", "Semibold",
}
